export const SET_WEBSITE_SEARCH_TEXT = 'SET_WEBSITE_SEARCH_TEXT';
export const SET_OPEN_WEBSITE_SEARCH = 'SET_OPEN_WEBSITE_SEARCH';
export const SET_OPEN_SIDEBAR_MENU = 'SET_OPEN_SIDEBAR_MENU';
export const SET_OPEN_CALENDAR_EVENT_MODAL = 'SET_OPEN_CALENDAR_EVENT_MODAL';
export const SET_CALENDAR_EVENTS = 'SET_CALENDAR_EVENTS';
export const SET_DARK_MODE = 'SET_DARK_MODE';
export const DATA_ERROR = 'DATA_ERROR';
